import { BusinessProfile, Client, Invoice } from "@/lib/types/invoice";

export const INITIAL_BUSINESS_PROFILE: BusinessProfile = {
  id: "biz_default",
  name: "Apex Studio Ltd.",
  logoUrl: "",
  email: "billing@apexstudio.io",
  phone: "+1 (555) 234-5678",
  website: "https://apexstudio.io",
  address: {
    street: "742 Evergreen Terrace, Suite 400",
    city: "San Francisco",
    state: "CA",
    postalCode: "94107",
    country: "United States",
  },
  taxId: "US-849204128",
  bankDetails: {
    bankName: "Silicon Valley Bank / First Republic",
    accountHolder: "Apex Studio Ltd.",
    accountNumber: "987654321045",
    routingNumber: "121000358",
    swiftCode: "SVBUS6S",
    paymentInstructions: "Please reference the invoice number on your wire transfer. Net 30 days.",
  },
  defaultCurrency: "USD",
  invoicePrefix: "INV",
  nextNumber: 6,
  defaultPaymentTerms: 14,
  defaultTaxRate: 10,
  defaultNotes: "Thank you for your business! We appreciate the partnership and look forward to working together again.",
  defaultTerms: "Payment is due within 14 days of invoice date. Invoices not paid within terms are subject to a 1.5% monthly late fee.",
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
};

export const INITIAL_CLIENTS: Client[] = [
  {
    id: "cli_acme",
    name: "Acme Corporation",
    companyName: "Acme Corp International",
    email: "finance@acmecorp.com",
    phone: "+1 (555) 891-2345",
    billingAddress: {
      street: "100 Industrial Parkway",
      city: "Austin",
      state: "TX",
      postalCode: "78701",
      country: "United States",
    },
    taxId: "TX-449102",
    notes: "Enterprise tier client. Requires PO number on all invoices.",
    createdAt: "2026-01-10T10:00:00.000Z",
    updatedAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "cli_luminary",
    name: "Luminary Media Group",
    companyName: "Luminary Digital",
    email: "accounts@luminarymedia.co",
    phone: "+1 (555) 732-9012",
    billingAddress: {
      street: "450 Broadway, 8th Floor",
      city: "New York",
      state: "NY",
      postalCode: "10013",
      country: "United States",
    },
    taxId: "NY-902184",
    notes: "Monthly retainer for brand creative & motion assets.",
    createdAt: "2026-01-15T11:30:00.000Z",
    updatedAt: "2026-01-15T11:30:00.000Z",
  },
  {
    id: "cli_solaris",
    name: "Solaris CleanTech",
    companyName: "Solaris Renewable Energy Inc.",
    email: "billing@solarisclean.com",
    phone: "+1 (555) 412-8700",
    billingAddress: {
      street: "1200 Innovation Way",
      city: "Denver",
      state: "CO",
      postalCode: "80202",
      country: "United States",
    },
    taxId: "CO-118274",
    notes: "Sustainable energy hardware portal redesign.",
    createdAt: "2026-02-01T09:15:00.000Z",
    updatedAt: "2026-02-01T09:15:00.000Z",
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: "inv_1",
    invoiceNumber: "INV-2026-0001",
    title: "Brand Strategy & Design System",
    poNumber: "PO-88219",
    referenceNumber: "REF-APEX-01",
    clientId: "cli_acme",
    clientSnapshot: {
      name: "Acme Corporation",
      companyName: "Acme Corp International",
      email: "finance@acmecorp.com",
      phone: "+1 (555) 891-2345",
      billingAddress: {
        street: "100 Industrial Parkway",
        city: "Austin",
        state: "TX",
        postalCode: "78701",
        country: "United States",
      },
      taxId: "TX-449102",
    },
    businessSnapshot: {
      name: "Apex Studio Ltd.",
      email: "billing@apexstudio.io",
      phone: "+1 (555) 234-5678",
      website: "https://apexstudio.io",
      address: {
        street: "742 Evergreen Terrace, Suite 400",
        city: "San Francisco",
        state: "CA",
        postalCode: "94107",
        country: "United States",
      },
      taxId: "US-849204128",
      bankDetails: {
        bankName: "Silicon Valley Bank / First Republic",
        accountHolder: "Apex Studio Ltd.",
        accountNumber: "987654321045",
        routingNumber: "121000358",
        paymentInstructions: "Wire transfer reference INV-2026-0001",
      },
    },
    issueDate: "2026-02-01",
    dueDate: "2026-02-15",
    currency: "USD",
    status: "paid",
    items: [
      {
        id: "item_1",
        name: "Design System Architecture & Tokens",
        description: "Figma component tokens, spacing variables, and accessibility audit.",
        quantity: 40,
        unit: "hrs",
        unitPrice: 150,
        discountRate: 0,
        taxRate: 10,
      },
      {
        id: "item_2",
        name: "Brand Identity Guidelines & Assets",
        description: "Vector iconography library and brand usage book.",
        quantity: 1,
        unit: "package",
        unitPrice: 3500,
        discountRate: 5,
        taxRate: 10,
      },
    ],
    invoiceDiscountRate: 0,
    invoiceDiscountAmount: 0,
    discountType: "percentage",
    shipping: 0,
    additionalCharges: 0,
    withholdingTaxRate: 0,
    notes: "Completed phase 1 deliverables. Thank you for working with Apex Studio!",
    terms: "Net 14 days.",
    payments: [
      {
        id: "pay_1",
        invoiceId: "inv_1",
        amount: 10147.5,
        date: "2026-02-14",
        method: "bank_transfer",
        reference: "WIRE-ACH-99201",
        notes: "Full payment settled via wire transfer.",
        createdAt: "2026-02-14T15:30:00.000Z",
      },
    ],
    branding: {
      templateId: "modern",
      accentColor: "#5B5FEF",
      fontFamily: "sans",
      showLogo: true,
      showBankDetails: true,
      footerText: "Apex Studio Ltd. · Registered in Delaware · www.apexstudio.io",
    },
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-02-14T15:30:00.000Z",
  },
  {
    id: "inv_2",
    invoiceNumber: "INV-2026-0002",
    title: "Q1 Digital Campaign & Motion Assets",
    poNumber: "PO-LUM-2026",
    clientId: "cli_luminary",
    clientSnapshot: {
      name: "Luminary Media Group",
      companyName: "Luminary Digital",
      email: "accounts@luminarymedia.co",
      phone: "+1 (555) 732-9012",
      billingAddress: {
        street: "450 Broadway, 8th Floor",
        city: "New York",
        state: "NY",
        postalCode: "10013",
        country: "United States",
      },
      taxId: "NY-902184",
    },
    businessSnapshot: {
      name: "Apex Studio Ltd.",
      email: "billing@apexstudio.io",
      phone: "+1 (555) 234-5678",
      website: "https://apexstudio.io",
      address: {
        street: "742 Evergreen Terrace, Suite 400",
        city: "San Francisco",
        state: "CA",
        postalCode: "94107",
        country: "United States",
      },
      taxId: "US-849204128",
      bankDetails: {
        bankName: "Silicon Valley Bank / First Republic",
        accountHolder: "Apex Studio Ltd.",
        accountNumber: "987654321045",
        routingNumber: "121000358",
      },
    },
    issueDate: "2026-03-01",
    dueDate: "2026-04-15",
    currency: "USD",
    status: "sent",
    items: [
      {
        id: "item_3",
        name: "3D Product Animation (4K 60fps)",
        description: "Three 15-second cinematic motion spots for social rollout.",
        quantity: 3,
        unit: "spots",
        unitPrice: 2200,
        discountRate: 0,
        taxRate: 8,
      },
      {
        id: "item_4",
        name: "Sound Design & Audio Mastering",
        description: "Bespoke score and surround sound mixing.",
        quantity: 1,
        unit: "package",
        unitPrice: 1200,
        discountRate: 0,
        taxRate: 8,
      },
    ],
    invoiceDiscountRate: 5,
    invoiceDiscountAmount: 0,
    discountType: "percentage",
    shipping: 0,
    additionalCharges: 150,
    withholdingTaxRate: 0,
    notes: "Master files dispatched via encrypted drive.",
    terms: "Payment due within 30 days.",
    payments: [],
    branding: {
      templateId: "bold",
      accentColor: "#2563EB",
      fontFamily: "sans",
      showLogo: true,
      showBankDetails: true,
      footerText: "Apex Studio Ltd. · Registered in Delaware · www.apexstudio.io",
    },
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "inv_3",
    invoiceNumber: "INV-2026-0003",
    title: "CleanTech Dashboard Prototype",
    clientId: "cli_solaris",
    clientSnapshot: {
      name: "Solaris CleanTech",
      companyName: "Solaris Renewable Energy Inc.",
      email: "billing@solarisclean.com",
      phone: "+1 (555) 412-8700",
      billingAddress: {
        street: "1200 Innovation Way",
        city: "Denver",
        state: "CO",
        postalCode: "80202",
        country: "United States",
      },
      taxId: "CO-118274",
    },
    businessSnapshot: {
      name: "Apex Studio Ltd.",
      email: "billing@apexstudio.io",
      phone: "+1 (555) 234-5678",
      website: "https://apexstudio.io",
      address: {
        street: "742 Evergreen Terrace, Suite 400",
        city: "San Francisco",
        state: "CA",
        postalCode: "94107",
        country: "United States",
      },
      taxId: "US-849204128",
      bankDetails: {
        bankName: "Silicon Valley Bank / First Republic",
        accountHolder: "Apex Studio Ltd.",
        accountNumber: "987654321045",
        routingNumber: "121000358",
      },
    },
    issueDate: "2026-01-05",
    dueDate: "2026-01-25", // In the past -> Overdue!
    currency: "USD",
    status: "overdue",
    items: [
      {
        id: "item_5",
        name: "Interactive Solar Array Dashboard",
        description: "Next.js + WebGL telemetry interface prototype.",
        quantity: 1,
        unit: "milestone",
        unitPrice: 4800,
        discountRate: 0,
        taxRate: 0,
      },
    ],
    invoiceDiscountRate: 0,
    invoiceDiscountAmount: 0,
    discountType: "percentage",
    shipping: 0,
    additionalCharges: 0,
    withholdingTaxRate: 0,
    notes: "Overdue reminder sent to accounts payable on Jan 28.",
    terms: "Net 20 days.",
    payments: [],
    branding: {
      templateId: "minimal",
      accentColor: "#0F172A",
      fontFamily: "mono",
      showLogo: true,
      showBankDetails: true,
      footerText: "Apex Studio Ltd. · All rights reserved",
    },
    createdAt: "2026-01-05T08:00:00.000Z",
    updatedAt: "2026-01-05T08:00:00.000Z",
  },
  {
    id: "inv_4",
    invoiceNumber: "INV-2026-0004",
    title: "Mobile App Wireframing & Usability Study",
    poNumber: "PO-ACME-409",
    clientId: "cli_acme",
    clientSnapshot: {
      name: "Acme Corporation",
      companyName: "Acme Corp International",
      email: "finance@acmecorp.com",
      phone: "+1 (555) 891-2345",
      billingAddress: {
        street: "100 Industrial Parkway",
        city: "Austin",
        state: "TX",
        postalCode: "78701",
        country: "United States",
      },
      taxId: "TX-449102",
    },
    businessSnapshot: {
      name: "Apex Studio Ltd.",
      email: "billing@apexstudio.io",
      phone: "+1 (555) 234-5678",
      website: "https://apexstudio.io",
      address: {
        street: "742 Evergreen Terrace, Suite 400",
        city: "San Francisco",
        state: "CA",
        postalCode: "94107",
        country: "United States",
      },
      taxId: "US-849204128",
      bankDetails: {
        bankName: "Silicon Valley Bank / First Republic",
        accountHolder: "Apex Studio Ltd.",
        accountNumber: "987654321045",
        routingNumber: "121000358",
      },
    },
    issueDate: "2026-03-10",
    dueDate: "2026-04-20",
    currency: "USD",
    status: "partially_paid",
    items: [
      {
        id: "item_6",
        name: "User Interviews & Synthetic Personas",
        description: "12 in-depth customer interviews and persona synthesis.",
        quantity: 20,
        unit: "hrs",
        unitPrice: 120,
        discountRate: 0,
        taxRate: 5,
      },
      {
        id: "item_7",
        name: "Interactive Figma Clickable Prototype",
        description: "iOS & Android high fidelity flow specifications.",
        quantity: 1,
        unit: "flow",
        unitPrice: 3200,
        discountRate: 0,
        taxRate: 5,
      },
    ],
    invoiceDiscountRate: 0,
    invoiceDiscountAmount: 0,
    discountType: "percentage",
    shipping: 0,
    additionalCharges: 0,
    withholdingTaxRate: 0,
    notes: "50% upfront retainer paid on March 12.",
    terms: "Balance due upon final deliverable submission.",
    payments: [
      {
        id: "pay_2",
        invoiceId: "inv_4",
        amount: 2940,
        date: "2026-03-12",
        method: "credit_card",
        reference: "STRIPE-CH-391823",
        notes: "50% deposit received via credit card.",
        createdAt: "2026-03-12T14:10:00.000Z",
      },
    ],
    branding: {
      templateId: "classic",
      accentColor: "#1E3A8A",
      fontFamily: "serif",
      showLogo: true,
      showBankDetails: true,
      footerText: "Apex Studio Ltd. · Registered in Delaware · www.apexstudio.io",
    },
    createdAt: "2026-03-10T11:00:00.000Z",
    updatedAt: "2026-03-12T14:10:00.000Z",
  },
  {
    id: "inv_5",
    invoiceNumber: "INV-2026-0005",
    title: "Brand Voice & Content Strategy Guidelines",
    clientId: "cli_luminary",
    clientSnapshot: {
      name: "Luminary Media Group",
      companyName: "Luminary Digital",
      email: "accounts@luminarymedia.co",
      phone: "+1 (555) 732-9012",
      billingAddress: {
        street: "450 Broadway, 8th Floor",
        city: "New York",
        state: "NY",
        postalCode: "10013",
        country: "United States",
      },
      taxId: "NY-902184",
    },
    businessSnapshot: {
      name: "Apex Studio Ltd.",
      email: "billing@apexstudio.io",
      phone: "+1 (555) 234-5678",
      website: "https://apexstudio.io",
      address: {
        street: "742 Evergreen Terrace, Suite 400",
        city: "San Francisco",
        state: "CA",
        postalCode: "94107",
        country: "United States",
      },
      taxId: "US-849204128",
      bankDetails: {
        bankName: "Silicon Valley Bank / First Republic",
        accountHolder: "Apex Studio Ltd.",
        accountNumber: "987654321045",
        routingNumber: "121000358",
      },
    },
    issueDate: "2026-03-25",
    dueDate: "2026-04-08",
    currency: "USD",
    status: "draft",
    items: [
      {
        id: "item_8",
        name: "Tone of Voice Matrix & Editorial Stylebook",
        description: "Draft guidelines currently undergoing internal team review.",
        quantity: 1,
        unit: "guide",
        unitPrice: 2400,
        discountRate: 0,
        taxRate: 8,
      },
    ],
    invoiceDiscountRate: 0,
    invoiceDiscountAmount: 0,
    discountType: "percentage",
    shipping: 0,
    additionalCharges: 0,
    withholdingTaxRate: 0,
    notes: "Draft invoice. Not yet transmitted to client.",
    terms: "Net 14 days upon issue.",
    payments: [],
    branding: {
      templateId: "modern",
      accentColor: "#5B5FEF",
      fontFamily: "sans",
      showLogo: true,
      showBankDetails: true,
      footerText: "Apex Studio Ltd. · Draft Document",
    },
    createdAt: "2026-03-25T16:00:00.000Z",
    updatedAt: "2026-03-25T16:00:00.000Z",
  },
];
